// scripts/backfill_customer_order_item_links.ts
//
// Repairs CustomerOrderItem rows that have no sourceItemId even though
// they clearly reference a real catalog item (itemNo/material is set).
// Same shape of bug as the original TransferOrderItem backfill this is
// modeled on: these rows predate sourceItemId being consistently
// populated, so anything resolving itemNo/isDraft/price via sourceItemId
// silently treats them as unlinked/Freizeile even though they aren't.
//
// For each row with no sourceItemId:
//   1. Try to match an existing Item by item_no_de, using itemNo first,
//      falling back to material.
//   2. If no match, create a new draft Item via ItemLinkService.resolveItem
//      — same creation path used everywhere else a draft Item is minted,
//      so it gets the same PRO category, supplier_id default, and unique
//      EAN as any other draft Item.
// Either way, sourceItemId is set on the CustomerOrderItem row and saved.
//
// Run with: ts-node scripts/backfill_customer_order_item_links.ts

import { AppDataSource } from "../config/database";
import { CustomerOrderItem } from "../models/customer_order_items";
import { Item } from "../models/items";
import { ItemLinkService } from "../services/item_link_service";
import { In, IsNull } from "typeorm";

async function run() {
  await AppDataSource.initialize();
  const queryRunner = AppDataSource.createQueryRunner();
  await queryRunner.connect();

  const orderItemRepo = queryRunner.manager.getRepository(CustomerOrderItem);
  const itemRepo = queryRunner.manager.getRepository(Item);

  const rows = await orderItemRepo.find({
    where: [{ sourceItemId: IsNull() }, { sourceItemId: "" as any }],
  });

  console.log(
    `Found ${rows.length} CustomerOrderItem row(s) with no linked Item.`,
  );

  // Pre-fetch every candidate Item by item_no_de in one batched query, so
  // each row's lookup below is just a Map read.
  const lookupCodes = Array.from(
    new Set(
      rows
        .map((r) => (r.itemNo || r.material || "").trim())
        .filter((code) => code.length > 0),
    ),
  );

  let itemByDeNo = new Map<string, Item>();
  if (lookupCodes.length > 0) {
    const foundItems = await itemRepo.find({
      where: { item_no_de: In(lookupCodes) },
    });
    itemByDeNo = new Map(
      foundItems.map((it) => [(it.item_no_de as string).trim(), it]),
    );
  }

  let linkedExisting = 0;
  let createdDraft = 0;
  let failed = 0;

  for (const row of rows) {
    await queryRunner.startTransaction();
    try {
      const code = (row.itemNo || row.material || "").trim();
      let matchedItem = code ? itemByDeNo.get(code) : undefined;

      if (!matchedItem) {
        // No existing Item to link to — go through the same
        // ItemLinkService.resolveItem path used everywhere else a draft
        // Item is created, so this backfill produces Items identical in
        // shape (PRO category, default supplier, autogenerated EAN,
        // isDraft: true) to any other draft Item in the system.
        matchedItem = await ItemLinkService.resolveItem(queryRunner, {
          itemName: row.itemName,
          itemNo: row.itemNo,
          material: row.material,
          specification: row.specification,
          weight: row.weight,
          purchasePrice: row.price,
          currency: undefined,
          photo: row.photo,
        });
        createdDraft++;
        console.log(
          `  CREATED draft Item ${matchedItem.id} for CustomerOrderItem ${row.id} (${row.itemName})`,
        );
      } else {
        linkedExisting++;
        console.log(
          `  LINKED CustomerOrderItem ${row.id} -> existing Item ${matchedItem.id} (${row.itemName})`,
        );
      }

      row.sourceItemId = String(matchedItem.id);
      await queryRunner.manager.getRepository(CustomerOrderItem).save(row);

      await queryRunner.commitTransaction();
    } catch (err) {
      await queryRunner.rollbackTransaction();
      failed++;
      console.error(
        `  FAILED: CustomerOrderItem ${row.id} (${row.itemName})`,
        err,
      );
    }
  }

  await queryRunner.release();
  console.log(
    `Done. Linked to existing: ${linkedExisting}, Created draft: ${createdDraft}, Failed: ${failed}`,
  );
  await AppDataSource.destroy();
  process.exit(failed > 0 ? 1 : 0);
}

run().catch((err) => {
  console.error("Backfill script crashed:", err);
  process.exit(1);
});
