import { QueryRunner } from "typeorm";
import { Item } from "../models/items";
import { Category } from "../models/categories";

export const ITEM_FIELD_MAP: Record<string, keyof Item> = {
  itemName: "item_name",
  material: "material",
  specification: "specification",
  weight: "weight",
  width: "width",
  height: "height",
  length: "length",
  purchasePrice: "price",
  currency: "currency",
  taric: "taricCode",
  taric_id: "taric_id",
  model: "model",
  ean: "ean",
  item_name_cn: "item_name_cn",
  item_name_de: "item_name_de",
  photo: "photo",
  pix_path: "pix_path",
  pix_path_eBay: "pix_path_eBay",
  cat_id: "cat_id",
  supplier_id: "supplier_id",
  is_rmb_special: "is_rmb_special",
  is_eur_special: "is_eur_special",
  isActive: "isActive",
  is_dim_weight_estimated: "is_dim_weight_estimated",
  remark: "remark",
  remark_ex: "remark_ex",
  remark_cn: "remark_cn",
  is_new: "is_new",
  is_npr: "is_npr",
  is_qty_dividable: "is_qty_dividable",
  is_dimension_special: "is_dimension_special",
  isLabelPrint: "isLabelPrint",
  transfer_price_EUR: "transfer_price_EUR",
  is_stock_item: "is_stock_item",
  stockEU: "stockEU",
  MSQ_EU: "MSQ_EU",
  stockCN: "stockCN",
  MSQ_CN: "MSQ_CN",
};

export class ItemLinkError extends Error {
  status: number;
  constructor(message: string, status = 400) {
    super(message);
    this.status = status;
  }
}

export const REQUESTED_ITEM_OWN_FIELDS = [
  "itemNo",
  "extraItems",
  "extraItemsDescriptions",
  "qty",
  "interval",
  "sampleQty",
  "expectedDelivery",
  "priority",
  "requestStatus",
  "comment",
  "extraNote",
  "asanaLink",
  "targetPrice",
  "annualPotential",
  "annualPotentialKEur",
  "isEstimated",
  "qualityCriteria",
  "attachments",
  "urgency1",
  "urgency2",
  "painPoints",
  "tagOrder",
  "parent_id",
] as const;

export function toRequestedItemOwnFields(
  payload: Record<string, any>,
): Record<string, any> {
  const own: Record<string, any> = {};
  for (const key of REQUESTED_ITEM_OWN_FIELDS) {
    if (payload[key] !== undefined) own[key] = payload[key];
  }
  return own;
}

/**
 * Resolves the id of the "PRO" category. Every draft Item created for a
 * RequestedItem/Inquiry request must always land in this category — this
 * is enforced unconditionally, never a fallback for an unset value, so a
 * payload's own cat_id is intentionally ignored on creation.
 */
export async function resolveProCategoryId(
  queryRunner: QueryRunner,
): Promise<number | undefined> {
  try {
    const categoryRepo = queryRunner.manager.getRepository(Category);
    const proCat = await categoryRepo.findOne({ where: { name: "PRO" } });
    return proCat?.id;
  } catch (e) {
    console.error("Failed to fetch default PRO category:", e);
    return undefined;
  }
}

const calculateEAN13Checksum = (ean12: string): number => {
  let sum = 0;
  for (let i = 0; i < 12; i++) {
    const d = parseInt(ean12[i], 10);
    sum += i % 2 === 0 ? d : d * 3;
  }
  const r = sum % 10;
  return r === 0 ? 0 : 10 - r;
};

const generateEAN13Candidate = (): string => {
  let ean12 = "";
  for (let i = 0; i < 12; i++) ean12 += Math.floor(Math.random() * 10);
  return `${ean12}${calculateEAN13Checksum(ean12)}`;
};

/**
 * Generates a fresh EAN-13 and guarantees it doesn't already exist on any
 * Item row, retrying on the rare collision. Used only when a new draft
 * Item is being created for a RequestedItem/Inquiry request — the EAN is
 * always autogenerated for these, never taken from the request payload.
 */
export async function generateUniqueEAN(
  queryRunner: QueryRunner,
): Promise<string> {
  const itemRepo = queryRunner.manager.getRepository(Item);
  for (let attempt = 0; attempt < 20; attempt++) {
    const candidate = generateEAN13Candidate();
    const existing = await itemRepo.findOne({ where: { ean: candidate } });
    if (!existing) return candidate;
  }
  throw new ItemLinkError(
    "Could not generate a unique EAN after multiple attempts",
    500,
  );
}

export class ItemLinkService {
  /**
   * Resolves the master Item for an incoming create payload.
   * - payload.itemId present -> validate & return the existing Item
   *   (no defaults applied — an existing Item's category/company/EAN
   *   are never touched by this path).
   * - otherwise -> create a new draft Item, always with:
   *     - cat_id forced to the "PRO" category, unconditionally (payload's
   *       own cat_id, if any, is ignored on creation)
   *     - customer_id taken from payload.customerId when supplied (the
   *       inquiry's customer, passed in by the caller — see
   *       inquiry_controller.ts call sites)
   *     - ean always autogenerated fresh and guaranteed unique — never
   *       taken from the payload
   */
  static async resolveItem(
    queryRunner: QueryRunner,
    payload: Record<string, any>,
  ): Promise<Item> {
    const itemRepo = queryRunner.manager.getRepository(Item);

    if (payload.itemId !== undefined && payload.itemId !== null) {
      const existing = await itemRepo.findOne({
        where: { id: payload.itemId },
      });
      if (!existing) {
        throw new ItemLinkError(`Item ${payload.itemId} not found`, 404);
      }
      return existing;
    }

    // Category is ALWAYS PRO for a newly-created draft Item — not a
    // fallback for a missing value, an unconditional override.
    const proCatId = await resolveProCategoryId(queryRunner);

    const resolvedPayload: any = {
      ...payload,
      cat_id: proCatId,
      supplier_id: payload.supplier_id ?? payload.supplierId ?? 1,
    };

    const itemData: Partial<Item> = {};
    for (const [payloadKey, itemKey] of Object.entries(ITEM_FIELD_MAP)) {
      if (resolvedPayload[payloadKey] !== undefined) {
        (itemData as any)[itemKey] = resolvedPayload[payloadKey];
      }
    }
    // Force PRO regardless of anything ITEM_FIELD_MAP may have picked up
    // from resolvedPayload.cat_id — belt and suspenders.
    itemData.cat_id = proCatId;

    if (itemData.item_name_de === undefined && payload.itemName) {
      itemData.item_name_de = payload.itemName;
    }

    if (itemData.item_no_de === undefined && payload.itemNo) {
      itemData.item_no_de = payload.itemNo;
    }

    if (
      payload.targetPrice !== undefined &&
      payload.targetPrice !== null &&
      payload.targetPrice !== ""
    ) {
      const parsedTarget = Number(payload.targetPrice);
      if (!isNaN(parsedTarget)) {
        itemData.sales_price = parsedTarget;
      }
    }

    // Company (customer_id) — taken from the inquiry this request belongs
    // to, passed in explicitly by the caller as payload.customerId. Never
    // inferred here; a request with no inquiry/customer context simply
    // leaves this unset.
    if (payload.customerId) {
      (itemData as any).customer_id = payload.customerId;
    }

    // EAN is always autogenerated for a new draft Item — the payload's
    // own ean (if ITEM_FIELD_MAP picked one up above) is intentionally
    // discarded here.
    itemData.ean = await generateUniqueEAN(queryRunner);

    itemData.isDraft = true;

    const draft = itemRepo.create(itemData);
    return itemRepo.save(draft);
  }

  static async syncItemFields(
    queryRunner: QueryRunner,
    item: Item,
    payload: Record<string, any>,
  ): Promise<Item> {
    const itemRepo = queryRunner.manager.getRepository(Item);
    let changed = false;
    for (const [payloadKey, itemKey] of Object.entries(ITEM_FIELD_MAP)) {
      if (payload[payloadKey] !== undefined) {
        (item as any)[itemKey] = payload[payloadKey];
        changed = true;
      }
    }
    return changed ? itemRepo.save(item) : item;
  }

  static async backfillItem(
    queryRunner: QueryRunner,
    baseFields: Record<string, any>,
    payload: Record<string, any>,
  ): Promise<Item> {
    return this.resolveItem(queryRunner, {
      ...baseFields,
      ...payload,
      itemId: undefined,
    });
  }

  static projectItemFields(item?: Item | null): Record<string, any> {
    if (!item) return {};
    const projected: Record<string, any> = {};
    for (const [payloadKey, itemKey] of Object.entries(ITEM_FIELD_MAP)) {
      projected[payloadKey] = (item as any)[itemKey];
    }
    return projected;
  }
}
